Fix normal docker run too

diff --git a/Docker/rootfs/etc/services.d/NetDaemonApp/run b/Docker/rootfs/etc/services.d/NetDaemonApp/run
--- a/Docker/rootfs/etc/services.d/NetDaemonApp/run
+++ b/Docker/rootfs/etc/services.d/NetDaemonApp/run
@@ -1,66 +1,52 @@
 #!/usr/bin/with-contenv bash
-echo "Starting NetDaemon Runner"
 
 declare daemondir="/daemon"
-declare is_custom_app_source=false
 
 if [ ! -d "/data" ]; then
     echo -e "\\033[31mMissing mapping to apps, please map '/data' to your apps folder\\033[0m" >&2
     exit 1
 fi
 
-if [[ "${NETDAEMON__APPLICATION_ASSEMBLY}" == *.csproj ]]; 
+if [ -z $NetDaemon_ApplicationAssembly ]
 then
-    echo -e "\\033[31mcsproj deployments are not supported in v3, use compiled option instead!\\033[0m" >&2
-    exit 1
-fi
+    echo -e "\\033[32mStarting NetDaemon V3 runtime ...\\033[0m" >&2
+    cd "${daemondir}"
+    exec dotnet NetDaemon.Host.Default.dll    
+else
+    if $NetDaemon_ApplicationAssembly == *.csproj ]]; 
+    then
+        echo -e "\\033[31mcsproj deployments are not supported in v3, use compiled option instead!\\033[0m" >&2
+        exit 1
+    fi
 
-if [[ "${NETDAEMON__APPLICATION_ASSEMBLY}" == *.csproj ]]; 
-then
-    echo -e "\\033[31mcsproj deployments are not supported in v3, use compiled option instead!\\033[0m" >&2
-    exit 1
-fi
-
-if [[ ! -z "${NETDAEMON__APPLICATION_ASSEMBLY}" ]] && [[ "${NETDAEMON__APPLICATION_ASSEMBLY}" != *".dll" ]];
-then
-    echo -e "\\033[31mAssembly needs to point to a .dll file!\\033[0m" >&2
-    exit 1
-fi
-
-if [[ "${NETDAEMON__APPLICATION_ASSEMBLY}" == *.dll ]]; 
-then 
-    is_custom_app_source=true
+    if $NetDaemon_ApplicationAssembly != *".dll" 
+    then
+        echo -e "\\033[31mAssembly needs to point to a .dll file!\\033[0m" >&2
+        exit 1
+    fi
 
     # make path relative to data folder (/config/netdaemon if addon) 
     # if the path is a relative path
-    if [[ "${NETDAEMON__APPLICATION_ASSEMBLY}" != /* ]];
+    if [[ "${NetDaemon_ApplicationAssembly}" != /* ]];
     then
-        export NETDAEMON__APPLICATION_ASSEMBLY="/data/${NETDAEMON__APPLICATION_ASSEMBLY}"
+        export NetDaemon_ApplicationAssembly="/data/${NetDaemon_ApplicationAssembly}"
     fi 
 
     # The provided application source is ether a project or pre-compiled .Net application
-    if [ ! -f ${NETDAEMON__APPLICATION_ASSEMBLY} ];
+    if [ ! -f ${NetDaemon_ApplicationAssembly} ];
     then
         
-        echo -e "\\033[31mThe assembly ${NETDAEMON__APPLICATION_ASSEMBLY} cannot be found. Please check the settings.\\033[0m" >&2
+        echo -e "\\033[31mThe assembly ${NetDaemon_ApplicationAssembly} cannot be found. Please check the settings.\\033[0m" >&2
         exit 1
     fi
-fi
+    echo -e "\\033[32mStarting NetDaemon V3 pre-built runtime using assembly ${NetDaemon_ApplicationAssembly}...\\033[0m" >&2
+    cd "$(dirname "${NetDaemon_ApplicationAssembly}")" || echo -e "\\033[31mCould not change directory to run project\\033[0m" >&2
 
-if  [[ $is_custom_app_source == false ]]; then
-    echo -e "\\033[32mRunning NetDaemon at ${daemondir}...\\033[0m" >&2
-    cd "${daemondir}"
-    exec dotnet NetDaemon.Host.Default.dll
-else 
-    # This is a pre-built deamon
-    echo -e "\\033[32mRunning the pre-built NetDaemon at ${NETDAEMON__APPLICATION_ASSEMBLY}...\\033[0m" >&2
-    cd "$(dirname "${NETDAEMON__APPLICATION_ASSEMBLY}")" || echo -e "\\033[31mCould not change directory to run project\\033[0m" >&2
-
-    if [[ "${PWD}" != "$(dirname "${NETDAEMON__APPLICATION_ASSEMBLY}")" ]]; then
+    if [[ "${PWD}" != "$(dirname "${NetDaemon_ApplicationAssembly}")" ]]; then
         echo -e "\\033[31mCould not change directory to run custom project\\033[0m" >&2
         exit 1
     fi
-    runme="$(basename "${NETDAEMON__APPLICATION_ASSEMBLY}")" 
+    runme="$(basename "${NetDaemon_ApplicationAssembly}")" 
     exec dotnet $runme
 fi
 
