Pull config out of RunnerService (#158)
* Context

* Post merge clean.

* Update client.
Add support for context.
Move things around a little.

* Fix name, also in an attempt to re-run tests on build server.

* Pull config out of runner service, use .net core built-in configuration.

Environment variables take preference over daemon_config.

* * Break apart HA settings from NetDaemon settings

* Remove HostBuilderExtensions
 - No need to generate a sample config file.  It now comes with one (appsettings.json)
 - No need to add json or env variables as generic host add these automatically

Runner.cs
* Pulled HassIO config file to environment variables out and into its own method (readability)
 - Comment out HASSCLIENT_MSGLOGLEVEL, couldn't see any usages
 - Comment out HASS_RUN_PROJECT_FOLDER, couldn't see any usages
* Register HA and ND settings in IOC

RunnerService.cs
* Inject settings
* Extract generate entities code into its own method (readability)

* PR comments.  Default config host value should be localhost.

* PR comments.

* PR comments.

* Move hosting code to Service.

* PR comments.

These are used by hass client.

* Update some docker variables.

* Allow changing of minimum log level by config or environment variables.

* Update project folder variable.

diff --git a/Docker/rootfs/etc/services.d/NetDaemon/run b/Docker/rootfs/etc/services.d/NetDaemon/run
--- a/Docker/rootfs/etc/services.d/NetDaemon/run
+++ b/Docker/rootfs/etc/services.d/NetDaemon/run
@@ -9,9 +9,9 @@ set -e
 declare runtype="Service"
 declare daemondir="/daemon"
 
-cd "${HASS_RUN_PROJECT_FOLDER}" || echo -e "\\033[31mCould not change directory to run project\\033[0m" >&2
+cd "${NETDAEMON__PROJECTFOLDER}" || echo -e "\\033[31mCould not change directory to run project\\033[0m" >&2
 
-if [[ "${PWD}" != "${HASS_RUN_PROJECT_FOLDER}" ]]; then
+if [[ "${PWD}" != "${NETDAEMON__PROJECTFOLDER}" ]]; then
     exit 1
 fi
 
